apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: reporthub
type: Opaque
stringData:
  APP_KEY: base64:8kUUHD9/QRY5eEOtXm9jxRC1zruWtYDpYc9BeTWgO4U=
  DB_PASSWORD: password
  MAIL_PASSWORD: ""
